name: Auto Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: lukka/get-cmake@latest
   
      - name: Setup Qt
        uses: jurplel/install-qt-action@latest
        with:
          version: '6.8.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          setup-python: 'false'

      - name: Configure CMake
        run: cmake -B Build -S . -G "Ninja"

      - name: Build
        run: cmake --build Build --config Release
